import { useMemo } from 'react'
import type { ReactNode } from 'react'
import { CircleNotch, GitBranch, Play, Pulse, ShieldCheck, Sparkle, UsersThree } from '@phosphor-icons/react'
import { GlassNav } from '../components/GlassNav'
import { DoubleBezel } from '../components/DoubleBezel'
import { IslandButton } from '../components/IslandButton'
import { Notice } from '../components/Notice'
import { Reveal } from '../components/Reveal'
import { useLiveDemo } from '../hooks/useLiveDemo'
import '../styles/theme.css'

const HEAT_WEIGHTS = [
  0, 0, 1, 2, 1, 0, 0, 1, 1, 2, 3, 2, 1, 0, 0, 2, 3, 3, 2, 1, 0, 1, 1, 2, 2, 3, 1, 0, 0, 1, 1, 2, 3,
  2, 1, 1, 2, 3, 2, 1, 0, 0, 2, 3, 3, 2, 1, 1, 0, 0, 1, 2, 3, 3, 2, 1, 1, 0, 1, 2, 2, 1, 0, 0, 1, 2,
  3, 2, 1, 1, 1, 2, 2, 3, 3, 2, 1, 0, 0, 1, 2, 2, 1, 0, 1, 1, 2, 3, 2, 1, 0, 0, 2, 3, 3, 2, 1, 0,
]

const HEAT_SHADES = [
  'var(--surface-3)',
  'color-mix(in srgb, var(--accent) 25%, var(--surface-3))',
  'color-mix(in srgb, var(--accent) 55%, var(--surface-3))',
  'var(--accent)',
]

const NAV_LINKS = [
  { label: 'How it works', href: '#how' },
  { label: 'Features', href: '#features' },
  { label: 'Sample insight', href: '#sample' },
]

const TRUST_POINTS = [
  { icon: ShieldCheck, text: 'Tokens encrypted at rest' },
  { icon: GitBranch, text: 'read:user + repo scopes only' },
  { icon: Pulse, text: 'No background jobs, ever' },
]

const FEATURES = [
  {
    icon: Sparkle,
    title: 'AI insights',
    description:
      'Commit activity summarized into a short read on delivery pace and risk — generated by Gemini, on request.',
    span: 'lg:col-span-3',
  },
  {
    icon: GitBranch,
    title: 'GitHub sync',
    description: 'Pulls repos and commits directly from the account you connect — no CI hooks or webhooks to configure.',
    span: 'lg:col-span-2',
  },
  {
    icon: UsersThree,
    title: 'Role-scoped visibility',
    description:
      'Managers see the people who report to them, admins see the org, members see themselves. Nothing to configure per-report.',
    span: 'lg:col-span-2',
    pills: ['ADMIN', 'MANAGER', 'MEMBER'],
  },
]

function MeshBackdrop() {
  return (
    <div
      aria-hidden="true"
      className="pointer-events-none fixed inset-0 -z-10"
      style={{
        background:
          'radial-gradient(40% 35% at 8% 0%, var(--accent-soft), transparent), radial-gradient(35% 30% at 100% 8%, var(--accent-2-soft), transparent)',
      }}
    />
  )
}

function DemoIcon({ pending }: { pending: boolean }) {
  return pending ? (
    <CircleNotch weight="light" className="h-4 w-4 animate-spin motion-reduce:animate-none" />
  ) : (
    <Play weight="light" className="h-4 w-4" />
  )
}

function Eyebrow({ children }: { children: ReactNode }) {
  return (
    <span
      className="inline-flex items-center rounded-full px-3 py-1 text-[10px] font-medium uppercase tracking-[0.2em]"
      style={{ background: 'var(--accent-soft)', color: 'var(--accent)' }}
    >
      {children}
    </span>
  )
}

export default function Landing() {
  const heatCells = useMemo(
    () => HEAT_WEIGHTS.map((weight) => HEAT_SHADES[weight] ?? HEAT_SHADES[0]),
    [],
  )

  // Separate state per entry point so each shows its own pending label and error.
  const heroDemo = useLiveDemo()
  const ctaDemo = useLiveDemo()
  const demoBusy = heroDemo.pending || ctaDemo.pending

  return (
    <div className="dp-theme min-h-[100dvh]">
      <MeshBackdrop />

      <GlassNav links={NAV_LINKS} secondaryLink={{ label: 'Log in', to: '/login' }} cta={{ label: 'Connect GitHub', to: '/register' }} />

      {/* ---------- hero ---------- */}
      <section className="mx-auto max-w-6xl px-4 pb-24 pt-16 sm:px-6 sm:pt-24">
        <div className="mx-auto max-w-3xl text-center">
          <Reveal>
            <Eyebrow>Live for engineering teams</Eyebrow>
          </Reveal>

          <Reveal delay={0.05}>
            <h1
              className="mt-6 text-4xl font-extrabold leading-[1.05] tracking-tight sm:text-6xl lg:text-7xl"
              style={{ color: 'var(--text)' }}
            >
              Your team&rsquo;s commits already tell the story.{' '}
              <br className="hidden sm:block" />
              <span style={{ color: 'var(--text-muted)' }}>DevPulse reads it back to you.</span>
            </h1>
          </Reveal>

          <Reveal delay={0.1}>
            <p className="mx-auto mt-6 max-w-2xl text-base sm:text-lg" style={{ color: 'var(--text-muted)' }}>
              Connect GitHub, sync on demand, and get a plain-language read on what your team
              actually shipped — written by AI, grounded in real commit history, never a black box
              dashboard you have to decode yourself.
            </p>
          </Reveal>

          <Reveal delay={0.15}>
            <div className="mt-10 flex flex-col items-center justify-center gap-3 sm:flex-row">
              <IslandButton
                disabled={demoBusy}
                onClick={() => void heroDemo.launch()}
                icon={<DemoIcon pending={heroDemo.pending} />}
              >
                {heroDemo.pending ? 'Opening demo…' : 'Try the live demo'}
              </IslandButton>
              <IslandButton to="/register" variant="ghost">
                Connect your GitHub
              </IslandButton>
            </div>
            {heroDemo.error && (
              <Notice
                tone="error"
                message={heroDemo.error}
                onDismiss={heroDemo.clearError}
                className="mx-auto mt-5 max-w-md text-left"
              />
            )}
          </Reveal>

          <Reveal delay={0.2}>
            <p className="mt-5 text-xs" style={{ color: 'var(--text-dim)' }}>
              The demo is a read-only sample team &mdash; no sign-up or GitHub needed. Your own account
              requests <code className="font-mono">read:user</code> + <code className="font-mono">repo</code>{' '}
              scopes only.
            </p>
          </Reveal>
        </div>

        <div className="mx-auto mt-20 grid max-w-4xl gap-5 sm:grid-cols-5">
          <Reveal delay={0.1} className="sm:col-span-3">
            <DoubleBezel innerClassName="p-6">
              <svg viewBox="0 0 800 110" preserveAspectRatio="none" aria-hidden="true" className="block h-auto w-full">
                <line x1="0" y1="80" x2="800" y2="80" stroke="var(--hairline)" strokeWidth="1" />
                <path
                  d="M0,80 L90,80 L110,80 L128,20 L146,95 L164,80 L230,80 L248,80 L266,35 L284,80 L360,80 L420,80 L438,80 L456,10 L474,100 L492,80 L560,80 L620,80 L638,80 L656,28 L674,80 L750,80 L800,80"
                  fill="none"
                  stroke="var(--accent)"
                  strokeWidth="2.5"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                />
                <circle cx="128" cy="20" r="3.5" fill="var(--accent-2)" />
                <circle cx="266" cy="35" r="3.5" fill="var(--accent-2)" />
                <circle cx="456" cy="10" r="3.5" fill="var(--accent-2)" />
                <circle cx="656" cy="28" r="3.5" fill="var(--accent-2)" />
              </svg>
              <div className="mt-3 flex justify-between font-mono text-xs" style={{ color: 'var(--text-dim)' }}>
                <span>acme-web · last 14 days</span>
                <span>4 spikes detected</span>
              </div>
            </DoubleBezel>
          </Reveal>

          <Reveal delay={0.18} className="sm:col-span-2">
            <DoubleBezel innerClassName="p-6">
              <span
                className="flex items-center gap-1.5 font-mono text-[0.68rem] uppercase tracking-wide"
                style={{ color: 'var(--accent)' }}
              >
                <Sparkle weight="light" className="h-3.5 w-3.5" />
                Generated insight
              </span>
              <h3 className="mt-3 text-sm font-semibold" style={{ color: 'var(--text)' }}>
                Steady delivery pace, one risk area
              </h3>
              <p className="mt-2 text-xs leading-relaxed" style={{ color: 'var(--text-muted)' }}>
                Commit volume held steady this cycle. Most activity clustered in checkout-service,
                with a late-week spike touching payment retries.
              </p>
              <div
                className="mt-4 flex justify-between border-t pt-3 font-mono text-[0.68rem]"
                style={{ borderColor: 'var(--hairline-soft)', color: 'var(--text-dim)' }}
              >
                <span>repos: 6</span>
                <span>commits: 214</span>
              </div>
            </DoubleBezel>
          </Reveal>
        </div>

        <Reveal delay={0.25}>
          <div className="mx-auto mt-10 flex max-w-4xl flex-wrap items-center justify-center gap-x-8 gap-y-3">
            {TRUST_POINTS.map(({ icon: Icon, text }) => (
              <span key={text} className="inline-flex items-center gap-2 text-xs" style={{ color: 'var(--text-muted)' }}>
                <Icon weight="light" className="h-4 w-4" style={{ color: 'var(--accent)' }} />
                {text}
              </span>
            ))}
          </div>
        </Reveal>
      </section>

      <div className="mx-auto max-w-6xl px-4 sm:px-6">
        {/* ---------- how it works ---------- */}
        <section id="how" className="border-t py-24 sm:py-32" style={{ borderColor: 'var(--hairline-soft)' }}>
          <Reveal>
            <Eyebrow>How it works</Eyebrow>
            <h2 className="mt-4 max-w-2xl text-2xl font-bold tracking-tight sm:text-3xl" style={{ color: 'var(--text)' }}>
              Three steps, no background jobs running on your data.
            </h2>
            <p className="mt-4 max-w-2xl" style={{ color: 'var(--text-muted)' }}>
              Every sync and every insight is a deliberate action you take — DevPulse never polls
              GitHub or calls the model on a schedule.
            </p>
          </Reveal>

          <div className="mt-12 grid gap-5 md:grid-cols-3">
            {[
              {
                num: '01',
                title: 'Connect GitHub',
                body: (
                  <>
                    Authorize a scoped OAuth app. DevPulse only ever asks for{' '}
                    <span className="font-mono">read:user</span> and <span className="font-mono">repo</span> —
                    nothing broader.
                  </>
                ),
                fine: 'token encrypted at rest',
              },
              {
                num: '02',
                title: 'Sync on demand',
                body: 'Pull every accessible repo and your own commits — 90 days on first sync, a rolling 14-day window after that. Deduplicated, safe to re-run.',
                fine: 'no automatic background sync',
              },
              {
                num: '03',
                title: 'Generate an insight',
                body: "Turn the synced window into a short, plain-language summary — what shipped, where activity concentrated, what's worth a second look.",
                fine: 'Gemini-powered, on request',
              },
            ].map((step, i) => (
              <Reveal key={step.num} delay={0.08 * i}>
                <DoubleBezel size="md" innerClassName="flex h-full flex-col p-6">
                  <span className="font-mono text-xs" style={{ color: 'var(--accent)' }}>
                    {step.num}
                  </span>
                  <h3 className="mt-3 text-base font-semibold" style={{ color: 'var(--text)' }}>
                    {step.title}
                  </h3>
                  <p className="mt-2 flex-1 text-sm" style={{ color: 'var(--text-muted)' }}>
                    {step.body}
                  </p>
                  <span
                    className="mt-4 inline-flex w-fit rounded-full px-2.5 py-1 font-mono text-[0.68rem]"
                    style={{ background: 'var(--accent-soft)', color: 'var(--accent)' }}
                  >
                    {step.fine}
                  </span>
                </DoubleBezel>
              </Reveal>
            ))}
          </div>
        </section>

        {/* ---------- what gets synced ---------- */}
        <section className="border-t py-24 sm:py-32" style={{ borderColor: 'var(--hairline-soft)' }}>
          <div className="grid items-center gap-10 lg:grid-cols-2">
            <Reveal>
              <Eyebrow>What gets synced</Eyebrow>
              <h2 className="mt-4 text-2xl font-bold tracking-tight sm:text-3xl" style={{ color: 'var(--text)' }}>
                A 14-day window, refreshed whenever you ask.
              </h2>
              <ul className="mt-8 flex flex-col gap-4">
                {[
                  <>
                    <strong style={{ color: 'var(--text)' }}>First sync</strong> pulls 90 days across
                    every repo the account can access, so there&rsquo;s real history to read.
                  </>,
                  <>
                    <strong style={{ color: 'var(--text)' }}>Every sync after</strong> covers the last
                    14 days, deduplicated against what&rsquo;s already stored — re-run it as often as
                    you like.
                  </>,
                  <>
                    <strong style={{ color: 'var(--text)' }}>Nothing runs unattended.</strong> Sync and
                    insight generation are both actions you trigger, never a cron job on your repos.
                  </>,
                ].map((text, i) => (
                  <li key={i} className="flex gap-3">
                    <span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full" style={{ background: 'var(--accent)' }} />
                    <span style={{ color: 'var(--text-muted)' }}>{text}</span>
                  </li>
                ))}
              </ul>
            </Reveal>

            <Reveal delay={0.1}>
              <DoubleBezel innerClassName="p-6">
                <div className="grid grid-cols-[repeat(14,minmax(0,1fr))] gap-1">
                  {heatCells.map((background, index) => (
                    <div key={index} className="aspect-square rounded-[3px]" style={{ background }} />
                  ))}
                </div>
                <div className="mt-4 flex items-center gap-1.5 font-mono text-[0.68rem]" style={{ color: 'var(--text-dim)' }}>
                  <span>less</span>
                  {HEAT_SHADES.map((background) => (
                    <span key={background} className="h-2.5 w-2.5 rounded-[3px]" style={{ background }} />
                  ))}
                  <span>more</span>
                </div>
                <div className="mt-2 font-mono text-[0.7rem]" style={{ color: 'var(--text-dim)' }}>
                  example commit density · 14-day sync window
                </div>
              </DoubleBezel>
            </Reveal>
          </div>
        </section>

        {/* ---------- features ---------- */}
        <section id="features" className="border-t py-24 sm:py-32" style={{ borderColor: 'var(--hairline-soft)' }}>
          <Reveal>
            <Eyebrow>Built for the whole team</Eyebrow>
            <h2 className="mt-4 text-2xl font-bold tracking-tight sm:text-3xl" style={{ color: 'var(--text)' }}>
              Insight for managers, visibility for everyone.
            </h2>
          </Reveal>

          <div className="mt-12 grid gap-5 lg:grid-cols-5">
            {FEATURES.map((feature, i) => (
              <Reveal key={feature.title} delay={0.08 * i} className={feature.span}>
                <DoubleBezel innerClassName="flex h-full flex-col p-6">
                  <feature.icon weight="light" className="h-6 w-6" style={{ color: 'var(--accent)' }} />
                  <h3 className="mt-4 text-base font-semibold" style={{ color: 'var(--text)' }}>
                    {feature.title}
                  </h3>
                  <p className="mt-2 flex-1 text-sm" style={{ color: 'var(--text-muted)' }}>
                    {feature.description}
                  </p>
                  {feature.pills && (
                    <div className="mt-4 flex flex-wrap gap-1.5">
                      {feature.pills.map((pill) => (
                        <span
                          key={pill}
                          className="rounded-full px-2.5 py-1 font-mono text-[0.65rem]"
                          style={{ background: 'var(--surface-2)', color: 'var(--text-muted)' }}
                        >
                          {pill}
                        </span>
                      ))}
                    </div>
                  )}
                </DoubleBezel>
              </Reveal>
            ))}
          </div>
        </section>

        {/* ---------- sample insight ---------- */}
        <section id="sample" className="border-t py-24 sm:py-32" style={{ borderColor: 'var(--hairline-soft)' }}>
          <Reveal>
            <Eyebrow>Sample insight</Eyebrow>
            <h2 className="mt-4 text-2xl font-bold tracking-tight sm:text-3xl" style={{ color: 'var(--text)' }}>
              What comes back after a sync.
            </h2>
            <p className="mt-4 max-w-2xl" style={{ color: 'var(--text-muted)' }}>
              Real insights are generated from your own connected repos. This one is illustrative.
            </p>
          </Reveal>

          <Reveal delay={0.1}>
            <DoubleBezel className="mt-10" innerClassName="p-7" size="lg">
              <div className="flex flex-wrap items-center justify-between gap-3">
                <span className="font-mono text-xs uppercase tracking-wide" style={{ color: 'var(--accent)' }}>
                  Insight · generated 2026-09-24
                </span>
                <span
                  className="rounded-full px-2.5 py-1 font-mono text-[0.68rem]"
                  style={{ background: 'var(--surface-2)', color: 'var(--text-dim)' }}
                >
                  example output
                </span>
              </div>
              <p className="mt-5 max-w-2xl text-base leading-relaxed" style={{ color: 'var(--text)' }}>
                Over the last 14 days, the team merged 42 pull requests across 6 repositories, with
                most activity in checkout-service and design-system. Delivery pace was consistent
                week over week. One area to watch: three commits touching payment retry logic
                landed within an hour of each other late Thursday, outside the usual review window
                — worth a quick look before the next release.
              </p>
              <div className="mt-6 flex flex-wrap gap-8 border-t pt-5" style={{ borderColor: 'var(--hairline-soft)' }}>
                {[
                  ['214', 'commits'],
                  ['6', 'repos synced'],
                  ['42', 'PRs merged'],
                  ['1', 'risk flagged'],
                ].map(([value, label]) => (
                  <div key={label}>
                    <div className="font-mono text-lg font-semibold" style={{ color: 'var(--text)' }}>
                      {value}
                    </div>
                    <div className="font-mono text-[0.68rem]" style={{ color: 'var(--text-dim)' }}>
                      {label}
                    </div>
                  </div>
                ))}
              </div>
            </DoubleBezel>
          </Reveal>
        </section>

        {/* ---------- final cta ---------- */}
        <section id="cta" className="border-t py-24 sm:py-32" style={{ borderColor: 'var(--hairline-soft)' }}>
          <Reveal>
            <DoubleBezel innerClassName="flex flex-col items-start justify-between gap-8 p-8 lg:flex-row lg:items-center sm:p-10">
              <div>
                <h2 className="text-2xl font-bold tracking-tight sm:text-3xl" style={{ color: 'var(--text)' }}>
                  See it on a sample team, then bring your own.
                </h2>
                <p className="mt-3 max-w-md" style={{ color: 'var(--text-muted)' }}>
                  The live demo opens a read-only team with generated activity. When you&rsquo;re
                  ready, register and sync your first repo in about two minutes.
                </p>
                {ctaDemo.error && (
                  <Notice
                    tone="error"
                    message={ctaDemo.error}
                    onDismiss={ctaDemo.clearError}
                    className="mt-5 max-w-md"
                  />
                )}
              </div>
              <div className="flex shrink-0 flex-col gap-3 sm:flex-row">
                <IslandButton
                  disabled={demoBusy}
                  onClick={() => void ctaDemo.launch()}
                  icon={<DemoIcon pending={ctaDemo.pending} />}
                >
                  {ctaDemo.pending ? 'Opening demo…' : 'Try the live demo'}
                </IslandButton>
                <IslandButton to="/register" variant="ghost">
                  Connect GitHub
                </IslandButton>
              </div>
            </DoubleBezel>
          </Reveal>
        </section>

        <footer
          className="flex flex-wrap items-center justify-between gap-3 border-t py-10 font-mono text-xs"
          style={{ borderColor: 'var(--hairline-soft)', color: 'var(--text-dim)' }}
        >
          <span>DevPulse</span>
          <span>Developer intelligence for engineering teams</span>
        </footer>
      </div>
    </div>
  )
}
